### ISSUE TITLE
Speciel do-notation for view creation

### ISSUE THREAD

**Issue by paldepind** [Funkia/hareactive#10]
Currently in `examples/simple/index.ts` the view function looks like this:

```js
view({validB, lengthB}) {
  return Do(function*(): Iterator<Component<any>> {
    yield span("Please enter an email address:");
    const {inputValue: emailB} = yield input();
    yield br();
    yield text("The length of the email is ");
    yield text(lengthB);
    yield br();
    yield text("The address is ");
    yield text(validB.map(t => t ? "valid" : "invalid"));
    return Component.of({behaviors: [emailB], events: []});
  });
}
```

This uses the general do-notation form Jabz. Maybe it is worth it to create a modified overloaded do-notation for creating views. It could allow for

* yielding `string` and `string` valued behaviors directly instead of using the `text` function.
* yielding several components at once by wrapping them in array. This of course cannot be used when the return value of the component is needed, like with `input` in the example.
* Not needing to wrap the final return value with `Component.of`.

```js
view({validB, lengthB}) {
  return componentDo(function*(): Iterator<Component<any>> {
    yield span("Please enter an email address:");
    const {inputValue: emailB} = yield input();
    yield [
      br(),
      "The length of the email is ",
      text(lengthB),
      br(),
      "The address is ",
      validB.map(t => t ? "valid" : "invalid"),
    ];
    return {behaviors: [emailB], events: []};
  });
}
```

The downside is of course that complexity is increased. Additionally it might be harder to understand due to the extra magic that is going on.

**Comment by paldepind** [comment]
We could also go one step further an do:

```js
const main = component<Model, ViewBehaviors, ViewStreams>({
  model(...) ...,
  *view({validB, lengthB}): Iterator<Component<any>> {
    yield span("Please enter an email address:");
    const {inputValue: emailB} = yield input();
    yield [
      br(),
      "The length of the email is ",
      text(lengthB),
      br(),
      "The address is ",
      validB.map(t => t ? "valid" : "invalid"),
    ];
    return {behaviors: [emailB], events: []};
  };
}
```

Here the `view` function no longer calls `Do`. Instead it is itself a generator function and `component` will have to call `Do` on it. This is even more lightweight but also even more magic :confused:

**Comment by limemloh** [comment]
I really like the idea of hiding the Do function inside the framework. In this case I would say that it is worth the magic.

**Comment by paldepind** [comment]
I'm working on adding support for components with child components and it occurred to me that the code above is probably not a good example of a typical component. Because most components will have a single parent element. Like this counter component from `examples/counters/index.ts`:

```ts
const counter = component<CounterModelOut, CounterViewOut>({
  model({streams: [incrementClick, decrementClick]}) {
    return Do(function*(): Iterator<Now<any>> {
      const increment = map(_ => 1, incrementClick);
      const decrement = map(_ => -1, decrementClick);
      const count = B.stepper(
        0,
        scan((n, m) => Math.max(n + m, 0), 0, merge(increment, decrement))
      );
      return Now.of({count});
    });
  },
  view: ({count}) =>
    div(Do(function*() {
      yield text("Counter ");
      yield text(count);
      yield text(" ");
      const {click: increment} = yield button(" + ");
      yield text(" ");
      const {click: decrement} = yield button(" - ");
      yield br;
      return Component.of({streams: [increment, decrement]})
    }))
});
```

Here the `view` function doesn't use `Do` immediately. Instead it calls `div` and uses `Do` in its argument to `div`. Of course `div` could take a generator function an call `Do` on it. But that doesn't seem to make as much of a difference as it did before.
