### ISSUE TITLE
Spelling Subscription?

### ISSUE THREAD

**Issue by arlair** [Funkia/hareactive#14]
I am not sure if this is from another language, a real term, or it is meant to be subscription?

https://github.com/Funkia/hareactive/search?utf8=%E2%9C%93&q=subscribtion

**Comment by paldepind** [comment]
That is just me not being very good at spelling :cry:

Also, cool that you're checking out Hareactive. There's not much documentation yet. Feel free to ask if you have any questions or curiosities.

**Comment by arlair** [comment]
That's cool, at least you are good at programming ;)

Thanks. Yes, I am interested in functional programming. I am reading and trying to learn more functional techniques and bend my mind to be more declarative in my coding.

I am not convinced JavaScript/TypeScript is a good playground to learn functional programming. There seem to be many holes to fall in ;) I am currently writing some code in TypeScript. This library is very new, so do you recommend using it, or something else for functional TypeScript at the moment?

I guess the other question is regarding fantasy-land? I know the jabz project mentions there are some differences. Does this mean it will not play at all with fantasy-land, or are there any libraries that might be useful to use with the Funkia ecosystem?

**Comment by paldepind** [comment]
Haha :smile: Thank you.

Well, what language is best depends on how far down the rabbit hole you want to go :wink: Have you seen [Professor Frisby's Mosty Adequate Guide to Functional Programming](https://github.com/MostlyAdequate/mostly-adequate-guide). It uses JavaScript and I've heard some very fine things said about it. I think JavaScript can be a fine learning ground for functional programming with things such Ramda etc. But if you're up to learning a new language then dabbling at Haskell is a very great learning opportunity.

> This library is very new, so do you recommend using it, or something else for functional TypeScript at the moment?

No, I wouldn't currently recommend using it unless one is already familiar with FRP. But we hope to add great documentation later on. I haven't seen much functional stuff done with TypeScript. But TypeScript isn't better than plain JavaScript for functional programming. Having static types is really nice in general but they also make some functional patterns harder.

> I guess the other question is regarding fantasy-land? I know the jabz project mentions there are some differences. Does this mean it will not play at all with fantasy-land, or are there any libraries that might be useful to use with the Funkia ecosystem?

Jabz does not aim to be compatible with fantasy-land. Parts of it are similar but the differences are numerous enough that they aren't really compatible.

> are there any libraries that might be useful to use with the Funkia ecosystem?

I'm not sure what you're thinking of here. You could use any additional libraries. There are [a lot](https://github.com/stoeffel/awesome-fp-js) of functional libraries. But in particular Ramda is very useful for many things.

**Comment by arlair** [comment]
Yes, I have read through Professor Frisby and other Brian Lonsdorf material. I found it very helpful :).

Yes, I have noticed TypeScript sometimes appears to get in the way of functional programming. It is still relatively young and will hopefully keep improving :). Funkia interested me as a way to guide me in using TypeScript with functional programming and avoid those issues ;).

Recently I have been trying to understand the algebraic structures used in functional programming and what some of the functional terms mean. I was going to try start with some basics, like Maybe, Either as they sound really useful for some problems I have faced. Then I hope to build up from there as I learn more.

I have mainly used static languages. I am trying to keep an open mind and I have started to see some appeal in the way JavaScript works that I didn't in my previous use over the years ;)

I haven't read a lot of Haskell, but did start a book on OCaml. I found OCaml enlightening because it has functional programming at its core and guides the user more than JavaScript via its syntax, compiler and type system. Elm seems to be similarly strict. JavaScript lets me do pretty much anything, including many bad things ;)

My interest in functional programming came from being frustrated with async in C#, which led to Rx.NET and later RxJS, etc. I tried Cycle.js, but for various reasons moved to React, e.g. the large number of components and big ecosystem. BuckleScript and Reason sound like they may become interesting ways to use React with functional programming, but are very young. So for now I am trying baby steps into functional with my TypeScript code.

In terms of asking about libraries, it sounded like some of those other libraries would not be compatible due to different algebraic types, or have the same functionality as Funkia. I was also not sure whether it works with, or replaces streaming libraries like Flyd, Most, RxJS etc. It sounds like Funkia is trying to implement a Conal Elliott style of FRP, but as a learning person I'm not up to speed with what all of that means :) Anyway, I will try continue learning and send some more documentation pull requests as I read.

Thank you for your time and work.

**Comment by paldepind** [comment]
> Yes, I have noticed TypeScript sometimes appears to get in the way of functional programming. It is still relatively young and will hopefully keep improving :). Funkia interested me as a way to guide me in using TypeScript with functional programming and avoid those issues ;).

I agree that TypeScript can get in the way of functional programming. It seems to me like the projects initial focus has been on bringing C#/Java-like features and typing to JavaScript. However, in most problematic cases there fortunately are workarounds.

> Recently I have been trying to understand the algebraic structures used in functional programming and what some of the functional terms mean. I was going to try start with some basics, like Maybe, Either as they sound really useful for some problems I have faced. Then I hope to build up from there as I learn more.

I think [Learn you a Haskell for great good](http://learnyouahaskell.com/) has some great introductions to the most basic/common algebraic structures. At some point I hope Jabz will grow approachable documentation that explains these to a JavaScript audience.

> I haven't read a lot of Haskell, but did start a book on OCaml. I found OCaml enlightening because it has functional programming at its core and guides the user more than JavaScript via its syntax, compiler and type system. Elm seems to be similarly strict. JavaScript lets me do pretty much anything, including many bad things ;)

That is a very good point. It is helpful to learn in the context of a language that prohibits certain "bad" things and guides one in the right directions.

> My interest in functional programming came from being frustrated with async in C#, which led to Rx.NET and later RxJS, etc. I tried Cycle.js, but for various reasons moved to React, e.g. the large number of components and big ecosystem. BuckleScript and Reason sound like they may become interesting ways to use React with functional programming, but are very young. So for now I am trying baby steps into functional with my TypeScript code.

Yes. BuckleScript and Reason are very promising. Especially if one is coming from a OCaml background. I've never used OCaml so to me PureScript is more interesting due to its heavy influence from Haskell.

> In terms of asking about libraries, it sounded like some of those other libraries would not be compatible due to different algebraic types, or have the same functionality as Funkia. I was also not sure whether it works with, or replaces streaming libraries like Flyd, Most, RxJS etc. It sounds like Funkia is trying to implement a Conal Elliott style of FRP, but as a learning person I'm not up to speed with what all of that means :) Anyway, I will try continue learning and send some more documentation pull requests as I read.

We're trying to replace a bunch of things with Funkia :smile: Jabz sits in the same space as fantasy land, Hareactive is indeed and alternative to stream libraries like Flyd, Most RxJS etc. And Funnel is a framework. One big difference is our focus on purity. Hareactive is completely pure whereas almost all other stream libraries for JavaScript have impure aspects.

Unfortunately the available material on Conal Elliott style FRP is hard to approach. Especially is one does not know Haskell. To remedy this I'm currently working on a tutorial about classic FRP that is supposed to be beginner friendly. And potentially a stepping stone to using Hareactive. I'm don't know when it'll be done, but maybe it would be of interest to you?

> Thank you for your time and work.

Thank you for checking it out and for the spelling fixes :smile:
