### ISSUE TITLE
Future questions

### ISSUE THREAD

**Issue by arlair** [funkia/hareactive#19]
Firstly, I think the 0.0.9 javascript `node_modules/future.js` file in the npm release is not in sync with the `src/future.ts`. I can't find `sinkFuture` to import and it is not in the JavaScript file.

I was trying to figure out if it was possible to replace `Task` from [folktale's data.task](https://github.com/folktale/data.task) with the hareactive `Future` :).

these parts:

```
function read(path) {
  return new Task(function(reject, resolve) {
    fs.readFile(path, function(error, data) {
      if (error)  reject(error)
      else        resolve(data)
    })
  })
}
```

...

```
concatenated.fork(
  function(error) { throw error }
, function(data)  { console.log(data) }
)
```

**Comment by paldepind** [comment]
Thank you for letting me know. I will take a look at i :smile:

I think IO from Jabz may be a better replacement for folktale's data.task. The is some documentation [here](https://github.com/Funkia/jabz/blob/master/docs/io-tutorial.md). However it does not yet provide a function for converting node-style cps functions to IO.
