### ISSUE TITLE
Add scanCombine

### ISSUE THREAD

**Issue by paldepind** [funkia/hareactive#30]
```js
scanCombine([
  [prepend, (item, list) => [item].concat(list)],
  [removeKey, (keys, list) => list.filter(item => !contains(itemToKey(item), keys))],
], initial);
```

**Comment by jayrbolton** [comment]
Another way I've enjoyed doing this type of thing lately is to make the updater streams into a single stream of functions that I scan over:

```
const updaters = mergeAll([
  map(prepend, prependElemStream)
, map(filterOut, removeKeysStream)
])
const elems = scan((acc, fn) => fn(acc), initial, updaters)

const prepend = item => list => [item].concat(list)
const filterOut = keys => list => list.filter(item => !contains(itemToKey(item), keys))
```

**Comment by paldepind** [comment]
Interesting. Why do you prefer that approach?

**Comment by jayrbolton** [comment]
I don't think I really prefer it, was just generally thinking of ideas around aggregating state by using streams of updater functions. However I think `scanCombine` should be included, as I find it immediately useful in maybe 95%+ of UI components. Just a tangential comment, apologies

**Comment by paldepind** [comment]
Ok. Thank you for explaining.

> I don't think I really prefer it, was just generally thinking of ideas around aggregating state by using streams of updater functions.

On a related note. In Reactive Banana they have a function [`accumE`](http://hackage.haskell.org/package/reactive-banana-1.1.0.1/docs/Reactive-Banana-Combinators.html#v:accumE) that takes a stream of updater functions and uses them to accumulate state. The function has the type `MonadMoment m => a -> Event (a -> a) -> m (Event a)`. In Hareactive it whould be `accumS: <A>(intial: A, s: Stream<(a: A) => A>) => Stream<A>`.

**Comment by paldepind** [comment]
We've added `scanCombine` :smile:
