### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by AndrewRayCode** [funkia/hareactive#70]
As a newcomer to FRP topics, I tried to spin up a toy project gluing this library to the UI, but have struggled to get off the ground (say, with a counter) because there aren't quickstart examples in this project I can find

**Comment by limemloh** [comment]
You might want to take a look at the tests, although they might not be ideal to learn from.
Another option could be to take a look at the examples in [Turbine](https://github.com/funkia/turbine).
