### ISSUE TITLE
How To Cite Hareactive?

### ISSUE THREAD

**Issue by DSoko2** [funkia/hareactive#86]
We are using Hareactive in one of our projects and would like to cite it in a paper. Is there a preffered way by the core contributors to do so?

**Comment by paldepind** [comment]
Hi @DSoko2. That sounds really interesting. Could you please share some more about how you are using Hareactive and what you are doing?

I think the best way to cite the project would be using the names Simon Friis Vindum and Emil Gjørup and then link to the Hareactive GitHub repository. Please share a BibTeX entry that we can take a look at :)

**Comment by paldepind** [comment]
Also, I'd love to read a draft of your paper (and give feedback if you're interested). In case you're up for that please send it to vindum [at] cs.au.dk.

**Comment by DSoko2** [comment]
Thanks for the quick answer @paldepind! I'd suggest the following entry then:

```
@misc{hareactive,
	author={Simon Friis Vindum and Emil Gjørup},
	title={Hareactive: Purely Functional Reactive Programming Library},
	year={2019},
	note = {\url{https://github.com/funkia/hareactive}, last accessed: 2021-02-25},
}
```

Due to the review procedure I cannot give more information about what we are doing with it here right now, but I promise to send you a draft version in the next days; it would be amazing to get your feedback!

**Comment by paldepind** [comment]
Looks good to me. @limemloh probably would like to see the draft as well. His email is in his GitHub profile.

**Comment by limemloh** [comment]
Yes please, I would like a copy as well. :+1: 
I would like to be cited as Emil Holm Gjørup if possible :smiley:
